// 收益互换三张列表的字段契约。
// `key` 为接口字段 Key；`id` 为当前前端列配置使用的稳定标识。
// 展示层可继续使用本地演示字段，但接入接口时必须以 key 为准。
export const tableFormattingRules = {
  truncation: '金额和价格仅截断，不允许四舍五入。',
  pricePrecision: 'A 股股票 2 位、可转债 3 位、港股 3 位小数。',
  thousandsSeparator: '数值使用千分位，例如 9999.001 展示为 9,999.001。',
}

export const tableFieldDefinitions = {
  positions: [
    { id: 'operation', label: '操作', key: 'Operation', description: '平仓、追单；仅多头持仓显示。' },
    { id: 'code', label: '证券代码', key: 'StockCode', description: '与 ExchangeType 组合，展示为“代码.市场”。' },
    { id: 'name', label: '证券名称', key: 'StockName', description: '按证券代码和市场查询证券码表。' },
    { id: 'price', label: '成本价/最新价', key: 'CostPrice', description: '同时展示 CostPrice 与行情 LastPrice；最新价相对 PreClose 着色。' },
    { id: 'opening', label: '期初数量', key: 'Opening', description: '接口直接返回；空值按 0 展示。' },
    { id: 'holdingQty', label: '持仓数量', key: 'HoldingQty', description: '接口直接返回。' },
    { id: 'available', label: '可用数量', key: 'AvailableQty', description: '接口直接返回。' },
    { id: 'valueWan', label: '市值', key: 'MarketValue', description: 'LastPrice × HoldingQty / 10000，万亿缩写且截断两位。' },
    { id: 'marginOccupied', label: '占用保证金', key: 'MarginValue', description: 'HoldingQty × ImFactor × CostPrice；保证金率缺失时展示 --。' },
    { id: 'marginRate', label: '保证金率', key: 'MarginRate', description: 'ImFactor × 100%；空或非法值展示 --。' },
    { id: 'totalProfit', label: '总盈亏', key: 'TotalPnL', description: 'FloatPnL + ClosedPnL。' },
    { id: 'dailyRealizedProfit', label: '实现盈亏', key: 'ClosedPnL', description: '接口直接返回。' },
    { id: 'floatingProfit', label: '浮动盈亏', key: 'FloatPnL', description: '按多空方向由成本价、最新价和持仓数量计算。' },
    { id: 'account', label: '下单账户', key: 'FundAccount', description: '展示“下单账户 - 账户名称”。' },
    { id: 'market', label: '市场', key: 'ExchangeType', description: 'HK/US/CN，经 exchange_type 字典展示。' },
    { id: 'currency', label: '币种', key: 'Currency', description: '由证券码表按 ExchangeType + StockCode 查询。' },
    { id: 'direction', label: '多空方向', key: 'PositionSide', description: '1=多头，2=空头；取 long_short 字典。' },
    { id: 'orderType', label: '订单类型', key: 'OrderSourceType', description: '系统单或手工单；持仓按来源订单聚合展示。' },
    { id: 'algorithm', label: '执行算法', key: 'ExecutionAlgorithm', description: '订单执行算法，如 POV、DMA；持仓按来源订单聚合展示。' },
    { id: 'orderRemark', label: '下单备注', key: 'OrderRemark', description: '客户提交手工单时填写的备注。' },
    { id: 'traderRemark', label: '交易员备注', key: 'TraderRemark', description: '交易员处理手工单后返回的备注；系统单为空。' },
  ],
  orders: [
    { id: 'operation', label: '操作', key: 'Operation', description: '追单、改单、撤单，三个按钮始终显示。' },
    { id: 'code', label: '证券代码', key: 'StockCode', description: '与 ExchangeType 组合，展示为“代码.市场”。' },
    { id: 'name', label: '证券名称', key: 'StockName', description: '按证券代码和市场查询证券码表。' },
    { id: 'status', label: '订单状态', key: 'InstructionStatus', description: '取 instruction_status 字典。' },
    { id: 'side', label: '方向', key: 'EntrustBs', description: '1=买入，2=卖出；取 entrust_bs 字典。' },
    { id: 'attribute', label: '订单属性', key: 'InstructionProp', description: '限价单、市价单等，取 instruction_prop 字典。' },
    { id: 'price', label: '订单价格', key: 'EntrustPrice', description: '市价单、0 或空值展示 --。' },
    { id: 'orderValueNumber', label: '订单数量/金额', key: 'TotEntrustAmount', description: 'MonetaryQtyFlag=A 时展示 TotEntrustBalance，否则展示 TotEntrustAmount。' },
    { id: 'reportQuantity', label: '挂单数量', key: 'ReportAmount', description: '服务端上报数量；0 或空值展示 --。' },
    { id: 'fillProgress', label: '成交进度', key: 'BusinessAmount / TotEntrustAmount', description: '已成数量 ÷ 订单数量；订单数量为空或为 0 时展示 --。' },
    { id: 'filledQuantity', label: '已成数量', key: 'BusinessAmount', description: '接口直接返回；0 或空值展示 --。' },
    { id: 'filledPrice', label: '成交均价', key: 'BusinessPrice', description: 'BusinessBalance / BusinessAmount，数量为 0 时展示 --。' },
    { id: 'filledAmount', label: '成交金额', key: 'BusinessBalance', description: '接口直接返回，按币种展示。' },
    { id: 'canceledValue', label: '撤单数量/金额', key: 'WithdrawnAmount', description: '仅部撤、撤单状态有效；按数量或金额模式计算。' },
    { id: 'frozenMargin', label: '冻结保证金', key: 'FrozenMargin', description: '在途金额 × ImFactor；卖出或终态展示 --。' },
    { id: 'marginRate', label: '保证金率', key: 'MarginRate', description: 'ImFactor × 100%；由保证金接口按标的注入。' },
    { id: 'feedback', label: '备注', key: 'Remark', description: '非空时显示复制按钮和文本。' },
    { id: 'orderNo', label: '订单编号', key: 'InstructionNo', description: '展示 InitDate + ExchangeType + 补零后的编号；原始编号用于接口交互。' },
    { id: 'orderTime', label: '订单时间', key: 'CurrTime', description: '接口 HHmmss 转为 HH:mm:ss。' },
    { id: 'account', label: '下单账户', key: 'FundAccount', description: '展示“下单账户 - 账户名称”。' },
    { id: 'market', label: '市场', key: 'ExchangeType', description: 'HK/US/CN，经 exchange_type 字典展示。' },
    { id: 'openClose', label: '开平方向', key: 'OpenClose', description: '1=开，2=平；取 open_close 字典。' },
    { id: 'orderType', label: '订单类型', key: 'OrderSourceType', description: '系统单或手工单。' },
    { id: 'algorithm', label: '执行算法', key: 'ExecutionAlgorithm', description: '订单执行算法，如 POV、DMA。' },
    { id: 'orderRemark', label: '下单备注', key: 'OrderRemark', description: '客户提交手工单时填写的备注。' },
    { id: 'traderRemark', label: '交易员备注', key: 'TraderRemark', description: '交易员处理手工单后返回的备注；系统单为空。' },
  ],
  trades: [
    { id: 'side', label: '方向', key: 'EntrustBs', description: '1=买入，2=卖出；取 entrust_bs 字典。' },
    { id: 'code', label: '证券代码', key: 'StockCode', description: '与 ExchangeType 组合，展示为“代码.市场”。' },
    { id: 'name', label: '证券名称', key: 'StockName', description: '按证券代码和市场查询证券码表。' },
    { id: 'filledPrice', label: '成交价格', key: 'BusinessPrice', description: '价格不大于 0 时展示 --，否则按市场精度格式化。' },
    { id: 'filledQuantity', label: '成交数量', key: 'BusinessAmount', description: '千分位格式化，空值按 0 展示。' },
    { id: 'filledAmount', label: '成交金额', key: 'BusinessBalance', description: '千分位格式化并带币种标签。' },
    { id: 'filledTime', label: '成交时间', key: 'BusinessTime', description: '接口 HHmmss 转为 HH:mm:ss。' },
    { id: 'orderTime', label: '订单时间', key: 'CurrTime', description: '接口 HHmmss 转为 HH:mm:ss。' },
    { id: 'tradeNo', label: '成交编号', key: 'BusinessNo', description: '显示成交编号并支持复制。' },
    { id: 'entrustNo', label: '订单编号', key: 'InstructionNo', description: '展示加工编号，原始编号用于接口交互。' },
    { id: 'tradeDate', label: '交易日期', key: 'InitDate / TradeDate', description: '展示 8 位交易日期。' },
    { id: 'account', label: '下单账户', key: 'FundAccount', description: '展示“下单账户 - 账户名称”。' },
    { id: 'market', label: '市场', key: 'ExchangeType', description: 'HK/US/CN，经 exchange_type 字典展示。' },
    { id: 'feedback', label: '备注', key: 'Remark', description: '非空时显示复制按钮和文本。' },
    { id: 'openClose', label: '开平方向', key: 'OpenClose', description: '1=开，2=平；取 open_close 字典。' },
    { id: 'orderType', label: '订单类型', key: 'OrderSourceType', description: '系统单或手工单。' },
    { id: 'algorithm', label: '执行算法', key: 'ExecutionAlgorithm', description: '来源订单的执行算法，如 POV、DMA。' },
    { id: 'orderRemark', label: '下单备注', key: 'OrderRemark', description: '客户提交手工单时填写的备注。' },
    { id: 'traderRemark', label: '交易员备注', key: 'TraderRemark', description: '交易员处理手工单后返回的备注；系统单为空。' },
  ],
}

export const columnOptionsFor = table => tableFieldDefinitions[table]
  .filter(field => field.id !== 'operation')
  .map(({ id, label }) => [id, label])
